config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :mobile_releases
  resources :notifications
  resources :players
  resources :game_records
  mount ActionCable.server => '/cable'

  resources :game_streams do
    member do
      get :stream
    end
  end

  resources :messages
  resources :streaming_rooms do
    member do
      get :viewers
      get :chats
      get :gifts
    end
  end
  resources :playmates do
    member do
      get :conversations
      get :exclusive_contents
      get :streams
    end
  end
  resources :billing_addresses
  resources :buyers do
  end
  resources :option_items
  resources :option_groups do
  end
  resources :variations
  resources :products do
    member do
      post :upload_image
      post :add_tags
      delete :delete_tag
      delete :delete_image
    end
  end
  resources :categories
  resources :merchants do
    member do
      post :upload_image
      delete :delete_image
    end
  end
  resources :users, path: 'user' do
    member do
      patch :toggle_verification
    end
  end

  get 'profile', to: 'profile#index'
  get 'profile/change_password'
  patch 'profile/update_password'
  # devise_for :users
  get 'users/:id' => 'users#show'
  get 'home/index'
  root 'home#index'

  get 'confirm_email/:token', to: 'email_handler#confirm_email'

  namespace :api do
    namespace :v2 do
      get 'auth/connection_test'
      post 'auth/login'
      post 'auth/login_with_facebook'
      post 'auth/login_with_google'
      post 'auth/login_with_apple'
      get 'auth/profile'
      delete 'auth/logout'
      post 'auth/register'
      post 'auth/resend_confirmation_email'
      post 'auth/forgot_password'
      post 'auth/resend_forgot_password_code'
      post 'auth/verify_forgot_password_code'
      post 'auth/change_password'
      patch 'profile/update_profile'
      get 'latest_version' => 'version_checker#latest_version'

      resources :notifications, only: [:index]

      resources :locations do
        collection do
          get :regions
          get :provinces
          get :cities
        end
      end
      resources :networks, only: [:index]
      resources :roulettes, only: %i[index show] do
        member do
          post :spin_game
        end
        collection do
          get :my_prices
        end
      end
    end
    namespace :v1 do
      get 'auth/connection_test'
      post 'auth/login'
      post 'auth/login_with_facebook'
      post 'auth/login_with_google'
      post 'auth/login_with_apple'
      post 'auth/register_user'
      post 'auth/register_playmate'
      post 'auth/register_as_merchant'
      post 'auth/verify_code'
      post 'auth/resend_verification_code'
      post 'auth/forgot_password'
      post 'auth/verify_forgot_password_code'
      post 'auth/change_password'
      post 'auth/resend_forgot_password_code'
      post 'auth/broadcast_logout'
      post 'auth/send_confirmation_email'
      get 'auth/tokens'
      get 'auth/profile'

      post 'game/create_game'
      get 'game/join_game'
      post 'game/spin_game'
      post 'game/broadcast_game'
      post 'game/override_timer'
      get 'game/:id', to: 'game#show'

      resources :notifications do
        collection do
          get :in_app_notifications
        end
        member do
          post :read
        end
      end

      resources :mobile_releases do
        collection do
          get :check_for_updates
          post :register_new_install
        end
      end

      resources :stations

      resources :documents do
        collection do
          get :terms_and_conditions
          get :privacy_policy
        end
      end

      resources :quiz_games
    end
  end
end

app/controllers/api/v1/mobile_releases_controller.rb
class Api::V1::MobileReleasesController < Api::V1::ApiController
  before_action :set_mobile_release, only: %i[ show edit update destroy ]

  def index
    @page = params[:page] || 1
    @per = params[:per] || 10

    @mobile_releases = MobileRelease.all
    @count = @mobile_releases.count
    @mobile_releases = @mobile_releases.page(@page).per(@per)

    render json: {
      mobile_releases: @mobile_releases.as_json(), 
      types: {
        android_update_types: MobileRelease.android_update_types.keys,
        ios_update_types: MobileRelease.ios_update_types.keys
      },
      count: @count, 
      limit_value: @mobile_releases.limit_value,
      total_pages: @mobile_releases.total_pages,
      current_page: @mobile_releases.current_page,
      next_page: @mobile_releases.next_page,
      prev_page: @mobile_releases.prev_page,
    }
  end

  def check_for_updates
    render json: MobileRelease.all.last
  end

  def register_new_install
    @mobile_release = MobileRelease.find_by_build_code(params[:build_code])
    if @mobile_release.present?
      case params[:type]
      when "ios"
        count = @mobile_release.ios_number_of_installs || 0
        @mobile_release.ios_number_of_installs = count + 1
      when "android"
        count = @mobile_release.android_number_of_installs || 0
        @mobile_release.android_number_of_installs = count + 1
      else
        return render json: "Invalid type", status: :unprocessable_entity
      end
      @mobile_release.save
      render json: @mobile_release
    else
      render json: "Not Found", status: :not_found
    end

  end

  def show
    render json: @mobile_release
  end

  def create
    @mobile_release = MobileRelease.new(mobile_release_params)
    if @mobile_release.save
      render json: @mobile_release
    else
      render json: @mobile_release.errors, status: :unprocessable_entity
    end
  end

  def update
    if @mobile_release.update(mobile_release_params)
      render json: @mobile_release
    else
      render json: @mobile_release.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @mobile_release.destroy
    render json: {message: "Successfully Deleted"}
  end

  private

    def set_mobile_release
      @mobile_release = MobileRelease.find(params[:id])
    end


    def mobile_release_params
      # :android_number_of_installs 
      # :ios_number_of_installs
      params.require(:mobile_release).permit(:build_code, :android_update_type, :ios_update_type, :maintenance_mode)
    end
end

app/controllers/mobile_releases_controller.rb
class MobileReleasesController < ApplicationController
  before_action :set_mobile_release, only: %i[ show edit update destroy ]

  # GET /mobile_releases or /mobile_releases.json
  def index
    @mobile_releases = MobileRelease.all
  end

  # GET /mobile_releases/1 or /mobile_releases/1.json
  def show
  end

  # GET /mobile_releases/new
  def new
    @mobile_release = MobileRelease.new
  end

  # GET /mobile_releases/1/edit
  def edit
  end

  # POST /mobile_releases or /mobile_releases.json
  def create
    @mobile_release = MobileRelease.new(mobile_release_params)

    respond_to do |format|
      if @mobile_release.save
        format.html { redirect_to @mobile_release, notice: "Mobile release was successfully created." }
        format.json { render :show, status: :created, location: @mobile_release }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mobile_release.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mobile_releases/1 or /mobile_releases/1.json
  def update
    respond_to do |format|
      if @mobile_release.update(mobile_release_params)
        format.html { redirect_to @mobile_release, notice: "Mobile release was successfully updated." }
        format.json { render :show, status: :ok, location: @mobile_release }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mobile_release.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mobile_releases/1 or /mobile_releases/1.json
  def destroy
    @mobile_release.destroy
    respond_to do |format|
      format.html { redirect_to mobile_releases_url, notice: "Mobile release was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mobile_release
      @mobile_release = MobileRelease.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mobile_release_params
      params.require(:mobile_release).permit(:build_code, :android_update_type, :ios_update_type, :android_number_of_installs, :ios_number_of_installs, :maintenance_mode)
    end
end

app/views/mobile_releases/_form.html.erb
<%= simple_form_for(@mobile_release) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :build_code %>
    <%= f.input :android_update_type %>
    <%= f.input :ios_update_type %>
    <%= f.input :android_number_of_installs %>
    <%= f.input :ios_number_of_installs %>
    <%= f.input :maintenance_mode %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/mobile_releases/edit.html.erb
<h1>Editing Mobile Release</h1>

<%= render 'form', mobile_release: @mobile_release %>

<%= link_to 'Show', @mobile_release %> |
<%= link_to 'Back', mobile_releases_path %>

app/views/mobile_releases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mobile Releases</h1>

<table>
  <thead>
    <tr>
      <th>Build code</th>
      <th>Android update type</th>
      <th>Ios update type</th>
      <th>Android number of installs</th>
      <th>Ios number of installs</th>
      <th>Maintenance mode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mobile_releases.each do |mobile_release| %>
      <tr>
        <td><%= mobile_release.build_code %></td>
        <td><%= mobile_release.android_update_type %></td>
        <td><%= mobile_release.ios_update_type %></td>
        <td><%= mobile_release.android_number_of_installs %></td>
        <td><%= mobile_release.ios_number_of_installs %></td>
        <td><%= mobile_release.maintenance_mode %></td>
        <td><%= link_to 'Show', mobile_release %></td>
        <td><%= link_to 'Edit', edit_mobile_release_path(mobile_release) %></td>
        <td><%= link_to 'Destroy', mobile_release, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mobile Release', new_mobile_release_path %>

app/views/mobile_releases/new.html.erb
<h1>New Mobile Release</h1>

<%= render 'form', mobile_release: @mobile_release %>

<%= link_to 'Back', mobile_releases_path %>

app/views/mobile_releases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Build code:</strong>
  <%= @mobile_release.build_code %>
</p>

<p>
  <strong>Android update type:</strong>
  <%= @mobile_release.android_update_type %>
</p>

<p>
  <strong>Ios update type:</strong>
  <%= @mobile_release.ios_update_type %>
</p>

<p>
  <strong>Android number of installs:</strong>
  <%= @mobile_release.android_number_of_installs %>
</p>

<p>
  <strong>Ios number of installs:</strong>
  <%= @mobile_release.ios_number_of_installs %>
</p>

<p>
  <strong>Maintenance mode:</strong>
  <%= @mobile_release.maintenance_mode %>
</p>

<%= link_to 'Edit', edit_mobile_release_path(@mobile_release) %> |
<%= link_to 'Back', mobile_releases_path %>