config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :mobile_releases
  resources :notifications
  resources :players
  resources :game_records
  mount ActionCable.server => '/cable'

  resources :game_streams do
    member do
      get :stream
    end
  end

  resources :messages
  resources :streaming_rooms do
    member do
      get :viewers
      get :chats
      get :gifts
    end
  end
  resources :playmates do
    member do
      get :conversations
      get :exclusive_contents
      get :streams
    end
  end
  resources :billing_addresses
  resources :buyers do
  end
  resources :option_items
  resources :option_groups do
  end
  resources :variations
  resources :products do
    member do
      post :upload_image
      post :add_tags
      delete :delete_tag
      delete :delete_image
    end
  end
  resources :categories
  resources :merchants do
    member do
      post :upload_image
      delete :delete_image
    end
  end
  resources :users, path: 'user' do
    member do
      patch :toggle_verification
    end
  end

  get 'profile', to: 'profile#index'
  get 'profile/change_password'
  patch 'profile/update_password'
  # devise_for :users
  get 'users/:id' => 'users#show'
  get 'home/index'
  root 'home#index'

  get 'confirm_email/:token', to: 'email_handler#confirm_email'

  namespace :api do
    namespace :v2 do
      get 'auth/connection_test'
      post 'auth/login'
      post 'auth/login_with_facebook'
      post 'auth/login_with_google'
      post 'auth/login_with_apple'
      get 'auth/profile'
      delete 'auth/logout'
      post 'auth/register'
      post 'auth/resend_confirmation_email'
      post 'auth/forgot_password'
      post 'auth/resend_forgot_password_code'
      post 'auth/verify_forgot_password_code'
      post 'auth/change_password'
      patch 'profile/update_profile'
      get 'latest_version' => 'version_checker#latest_version'

      resources :notifications, only: [:index]

      resources :locations do
        collection do
          get :regions
          get :provinces
          get :cities
        end
      end
      resources :networks, only: [:index]
      resources :roulettes, only: %i[index show] do
        member do
          post :spin_game
        end
        collection do
          get :my_prices
        end
      end
    end
    namespace :v1 do
      get 'auth/connection_test'
      post 'auth/login'
      post 'auth/login_with_facebook'
      post 'auth/login_with_google'
      post 'auth/login_with_apple'
      post 'auth/register_user'
      post 'auth/register_playmate'
      post 'auth/register_as_merchant'
      post 'auth/verify_code'
      post 'auth/resend_verification_code'
      post 'auth/forgot_password'
      post 'auth/verify_forgot_password_code'
      post 'auth/change_password'
      post 'auth/resend_forgot_password_code'
      post 'auth/broadcast_logout'
      post 'auth/send_confirmation_email'
      get 'auth/tokens'
      get 'auth/profile'

      post 'game/create_game'
      get 'game/join_game'
      post 'game/spin_game'
      post 'game/broadcast_game'
      post 'game/override_timer'
      get 'game/:id', to: 'game#show'

      resources :notifications do
        collection do
          get :in_app_notifications
        end
        member do
          post :read
        end
      end

      resources :mobile_releases do
        collection do
          get :check_for_updates
          post :register_new_install
        end
      end

      resources :stations

      resources :documents do
        collection do
          get :terms_and_conditions
          get :privacy_policy
        end
      end

      resources :quiz_games
    end
  end
end

app/models/game_record.rb
class GameRecord < ApplicationRecord
  validates :game_id, presence: true, uniqueness: true
  validates :number_of_winners, presence: true
  validates :start_time, presence: true
  enum status: ["Ongoing", "Ended"]



  def self.lobby_time
    30
  end

  def players
    Player.where(game_id: game_id)
  end

  def remaining_time
    (start_time.to_time - DateTime.now.to_time)
  end

  def current_time
    DateTime.now.to_time
  end
end

app/controllers/game_records_controller.rb
class GameRecordsController < ApplicationController
  before_action :set_game_record, only: [:show, :edit, :update, :destroy]

  # GET /game_records
  # GET /game_records.json
  def index
    @game_records = GameRecord.all
  end

  # GET /game_records/1
  # GET /game_records/1.json
  def show
  end

  # GET /game_records/new
  def new
    @game_record = GameRecord.new
  end

  # GET /game_records/1/edit
  def edit
  end

  # POST /game_records
  # POST /game_records.json
  def create
    @game_record = GameRecord.new(game_record_params)

    respond_to do |format|
      if @game_record.save
        format.html { redirect_to @game_record, notice: 'Game record was successfully created.' }
        format.json { render :show, status: :created, location: @game_record }
      else
        format.html { render :new }
        format.json { render json: @game_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_records/1
  # PATCH/PUT /game_records/1.json
  def update
    respond_to do |format|
      if @game_record.update(game_record_params)
        format.html { redirect_to @game_record, notice: 'Game record was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_record }
      else
        format.html { render :edit }
        format.json { render json: @game_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_records/1
  # DELETE /game_records/1.json
  def destroy
    @game_record.destroy
    respond_to do |format|
      format.html { redirect_to game_records_url, notice: 'Game record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_record
      @game_record = GameRecord.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_record_params
      params.require(:game_record).permit(:game_id, :start_time, :winners)
    end
end

app/views/game_records/_form.html.erb
<%= simple_form_for(@game_record) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :game_id %>
    <%= f.input :start_time %>
    <%= f.input :winners %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/game_records/edit.html.erb
<h1>Editing Game Record</h1>

<%= render 'form', game_record: @game_record %>

<%= link_to 'Show', @game_record %> |
<%= link_to 'Back', game_records_path %>

app/views/game_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Game Records</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Start time</th>
      <th>Winners</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_records.each do |game_record| %>
      <tr>
        <td><%= game_record.game_id %></td>
        <td><%= game_record.start_time %></td>
        <td><%= game_record.winners %></td>
        <td><%= link_to 'Show', game_record %></td>
        <td><%= link_to 'Edit', edit_game_record_path(game_record) %></td>
        <td><%= link_to 'Destroy', game_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game Record', new_game_record_path %>

app/views/game_records/new.html.erb
<h1>New Game Record</h1>

<%= render 'form', game_record: @game_record %>

<%= link_to 'Back', game_records_path %>

app/views/game_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @game_record.game_id %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @game_record.start_time %>
</p>

<p>
  <strong>Winners:</strong>
  <%= @game_record.winners %>
</p>

<%= link_to 'Edit', edit_game_record_path(@game_record) %> |
<%= link_to 'Back', game_records_path %>